'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Afrit3
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DemonArena.Afrit3", GetType(Afrit3).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07A1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07A1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07A2A8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07A2A8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07A3A7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07A3A7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07A4A6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07A4A6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07A5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07A5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07B1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07B1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07B2B8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07B2B8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07B3B7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07B3B7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07B4B6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07B4B6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07B5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07B5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07C1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07C1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07C2C8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07C2C8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07C3C7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07C3C7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07C4C6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07C4C6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07C5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07C5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07D1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07D1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07D2D8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07D2D8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07D3D7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07D3D7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07D4D6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07D4D6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07D5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07D5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07E1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07E1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07E2E8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07E2E8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07E3E7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07E3E7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07E4E6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07E4E6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07E5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07E5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07F1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07F1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07F2F8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07F2F8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07F3F7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07F3F7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07F4F6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07F4F6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07F5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07F5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07G1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07G1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07G2G8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07G2G8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07G3G7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07G3G7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07G4G6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07G4G6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07G5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07G5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07H1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07H1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07H2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07H2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07H3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07H3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07H4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07H4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07H5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07H5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07H6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07H6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07H7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07H7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07H8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07H8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07I0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07I0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07J0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07J0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07K0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07K0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07L0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07L0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07M0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07M0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07N0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07N0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07O0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07O0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07P0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07P0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07Q0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07Q0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07R0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07R0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07S1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07S1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07S2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07S2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07S3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07S3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07S4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07S4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07S5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07S5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07S6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07S6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07S7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07S7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07S8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07S8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07T1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07T1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07T2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07T2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07T3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07T3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07T4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07T4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07T5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07T5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07T6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07T6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07T7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07T7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07T8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07T8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07U1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07U1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07U2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07U2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07U3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07U3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07U4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07U4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07U5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07U5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07U6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07U6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07U7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07U7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR07U8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR07U8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
