'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Afrit
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DemonArena.Afrit", GetType(Afrit).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06A1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06A1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06A2A8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06A2A8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06A3A7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06A3A7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06A4A6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06A4A6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06A5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06A5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06B1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06B1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06B2B8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06B2B8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06B3B7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06B3B7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06B4B6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06B4B6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06B5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06B5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06C1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06C1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06C2C8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06C2C8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06C3C7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06C3C7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06C4C6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06C4C6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06C5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06C5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06D1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06D1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06D2D8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06D2D8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06D3D7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06D3D7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06D4D6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06D4D6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06D5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06D5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06E1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06E1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06E2E8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06E2E8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06E3E7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06E3E7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06E4E6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06E4E6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06E5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06E5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06F1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06F1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06F2F8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06F2F8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06F3F7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06F3F7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06F4F6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06F4F6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06F5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06F5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06G1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06G1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06G2G8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06G2G8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06G3G7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06G3G7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06G4G6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06G4G6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06G5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06G5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06H1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06H1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06H2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06H2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06H3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06H3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06H4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06H4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06H5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06H5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06H6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06H6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06H7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06H7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06H8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06H8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06I0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06I0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06J0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06J0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06K0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06K0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06L0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06L0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06M0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06M0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06N0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06N0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06O0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06O0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06P0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06P0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06Q0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06Q0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06R0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06R0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06S1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06S1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06S2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06S2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06S3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06S3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06S4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06S4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06S5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06S5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06S6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06S6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06S7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06S7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06S8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06S8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06T1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06T1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06T2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06T2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06T3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06T3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06T4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06T4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06T5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06T5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06T6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06T6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06T7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06T7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06T8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06T8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06U1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06U1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06U2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06U2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06U3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06U3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06U4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06U4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06U5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06U5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06U6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06U6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06U7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06U7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property FR06U8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FR06U8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
