'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1026
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ArachNorb
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DemonArena.ArachNorb", GetType(ArachNorb).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend Shared ReadOnly Property ACNBA1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNBA1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNBA2A8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNBA2A8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNBA3A7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNBA3A7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNBA4A6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNBA4A6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNBA5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNBA5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNBB1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNBB1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNBB2B8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNBB2B8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNBB3B7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNBB3B7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNBB4B6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNBB4B6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNBB5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNBB5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNBC1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNBC1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNBC2C8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNBC2C8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNBC3C7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNBC3C7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNBC4C6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNBC4C6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNBC5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNBC5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNBD0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNBD0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNBE0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNBE0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNBF0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNBF0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNBG0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNBG0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNBH0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNBH0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNFI1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNFI1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNFI2I8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNFI2I8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNFI3I7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNFI3I7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNFI4I6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNFI4I6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ACNFI5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ACNFI5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
