'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1026
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Disciple
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DemonArena.Disciple", GetType(Disciple).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend Shared ReadOnly Property DISCA1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCA1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCA2A8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCA2A8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCA3A7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCA3A7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCA4A6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCA4A6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCA5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCA5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCB1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCB1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCB2B8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCB2B8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCB3B7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCB3B7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCB4B6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCB4B6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCB5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCB5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCC1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCC1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCC2C8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCC2C8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCC3C7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCC3C7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCC4C6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCC4C6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCC5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCC5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCD1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCD1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCD2D8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCD2D8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCD3D7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCD3D7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCD4D6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCD4D6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCD5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCD5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCE1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCE1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCE2E8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCE2E8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCE3E7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCE3E7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCE4E6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCE4E6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCE5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCE5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCF1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCF1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCF2F8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCF2F8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCF3F7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCF3F7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCF4F6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCF4F6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCF5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCF5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCG1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCG1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCG2G8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCG2G8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCG3G7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCG3G7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCG4G6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCG4G6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCG5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCG5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCH0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCH0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCI0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCI0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCJ0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCJ0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCK0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCK0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCL0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCL0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCM0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCM0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCN0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCN0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DISCO0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DISCO0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
